I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 513, in script
    python:
  File "game/script.rpy", line 514, in <module>
    matrix_A = [[1][2][3]]
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 513, in script
    python:
  File "C:\Users\tooki\OneDrive - University of Waterloo\CHE 120\The Waterloo Games\renpy-8.3.3-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\tooki\OneDrive - University of Waterloo\CHE 120\The Waterloo Games\renpy-8.3.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 514, in <module>
    matrix_A = [[1][2][3]]
  File "C:\Users\tooki\OneDrive - University of Waterloo\CHE 120\The Waterloo Games\renpy-8.3.3-sdk\renpy\revertable.py", line 214, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
theWaterlooGames 1.0
Sun Nov 24 16:55:31 2024
